# 数据库
[[DB]]
Name="phoenix_house"
Comment="梧桐屋"

# 表
[[DB.Tables]]
Name="user"
Comment="用户表"
# 列集合
Columns=[{Name="dd",StructTag="dd",StorageKey="dd",FieldType="int",MaxLen=64,MinLen=10,Precision=10,Scale=2,AutoInc=false,IsNonNegative=false,DefaultVal="",IsSensitive=false,IsImmutable=false,IsOptional=false,Enumerable=true,EnumVals=["a","b","c","d"],IsPrimary=true,PkName="pk_user_id",IsForeignKey=true,FkName="fk_user_id",IsUnique=true,UidxName="uidx_userID",IsIndex=true,IdxName="idx_userID",Comment="用户ID"},{Name="user_ID",StructTag="dd",StorageKey="dd",FieldType="int",MaxLen=64,MinLen=10,Precision=10,Scale=2,AutoInc=false,IsNonNegative=false,DefaultVal="",IsSensitive=false,IsImmutable=false,IsOptional=false,Enumerable=true,EnumVals=["a","b","c","d"],IsPrimary=true,PkName="pk_user_id",IsForeignKey=true,FkName="fk_user_id",IsUnique=true,UidxName="uidx_userID",IsIndex=true,IdxName="idx_userID",Comment="用户ID"}]

Edges=[{From="tag",FromName="tags",To="pet",ToName="pets",RefName="user"},{To="group",ToName="groups",RefName="user"}]

[[DB.Tables]]
Name="tag"
Comment="标签表"
Columns=[{Name="dd",StructTag="dd",StorageKey="dd",FieldType="int",MaxLen=64,MinLen=10,Precision=10,Scale=2,AutoInc=false,IsNonNegative=false,DefaultVal="",IsSensitive=false,IsImmutable=false,IsOptional=false,Enumerable=true,EnumVals=["a","b","c","d"],IsPrimary=true,PkName="pk_user_id",IsForeignKey=true,FkName="fk_user_id",IsUnique=true,UidxName="uidx_userID",IsIndex=true,IdxName="idx_userID",Comment="用户ID"},{Name="user_ID",Struct_tag="dd",StorageKey="dd",FieldType="int",MaxLen=64,MinLen=10,Precision=10,Scale=2,AutoInc=false,IsNonNegative=false,DefaultVal="",IsSensitive=false,IsImmutable=false,IsOptional=false,Enumerable=true,EnumVals=["a","b","c","d"],IsPrimary=true,PkName="pk_user_id",IsForeignKey=true,FkName="fk_user_id",IsUnique=true,UidxName="uidx_userID",IsIndex=true,IdxName="idx_userID",Comment="用户ID"}]