// Code generated by gcodex, DO NOT EDIT.
// Output:./dist/ent/schema/*.go
// TODO: Extension API support HTTP Restfull API/grpc logging/metric/tracing
// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.
package gcodex

//go generate
// 根据 AST 生成 service 层源码